let prices = document.querySelectorAll(".prices");
let total = 0;
prices.forEach(price => total += parseFloat(price.textContent));
let table = document.getElementById("groceryTable");
let row = document.createElement("tr");
let cell = document.createElement("td");
cell.colSpan = 2;
cell.textContent = "Total: " + total;
row.appendChild(cell);
table.appendChild(row);
